name: dgauge_flutter_example
description: "Demonstrates how to use the dgauge_flutter plugin."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  dgauge_flutter:
    path: ../

  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.14
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  qr_code_scanner_plus: ^2.0.12
  equatable: ^2.0.7
  permission_handler: ^12.0.1
  logger: ^2.6.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
